- name: reboot
  become: true
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0

- name: wait for reboot to finish
  wait_for: >
    host={{ ansible_default_ipv4.address }}
    port=22
    delay=10
    timeout=120
  delegate_to: localhost