
#MiniDLNA
- name: MiniDLNA - apt-get
  become: true
  apt:
    name: minidlna
    dpkg_options: 'force-confold,force-confdef'
    state: present

- name: MiniDLNA - systemd
  become: true
  systemd:
    name: minidlna
    state: stopped
    enabled: no

- name: MiniDLNA - install djmount
  become: true
  apt: name=djmount state=present

#Ashuffle
- name: Autoshuffle - git checkout autoshuffle
  become: true
  git:
    repo:  git://github.com/Joshkunz/ashuffle.git
    dest: /home/pi/ashuffle

- name: Autoshuffle - make
  become: true
  shell: chdir=/home/pi/ashuffle make creates=/usr/local/bin/ashuffle

- name: Ashuffle - copy package
  become: true
  copy:
    src: /home/pi/ashuffle/ashuffle
    dest: /usr/local/bin/ashuffle
    remote_src: yes

#MPD Audio Scrobbler
- name: MPD Audio Scrobbler - git checkout MPD Audio Scrobbler
  become: true
  git:
    repo:  git://github.com/hrkfdn/mpdas
    dest: /home/pi/mpdas

- name: MPD Audio Scrobbler - make
  become: true
  shell: chdir=/home/pi/mpdas make creates=/usr/local/bin/mpdas

- name: MPD Audio Scrobbler - copy package
  become: true
  copy:
    src: /home/pi/mpdas/mpdas
    dest: /usr/local/bin/mpdas
    remote_src: yes

- name: MPD Audio Scrobbler - copy config file
  become: true
  copy: 
    src: /home/pi/rel-stretch/usr/local/etc/mpdasrc.default
    dest: /usr/local/etc/mpdasrc
    mode: 0755
    remote_src: yes

#Shairport-sync
- name: Shairport-sync - install packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - autoconf
    - libtool
    - libdaemon-dev
    - libasound2-dev
    - libpopt-dev
    - libconfig-dev
    - avahi-daemon
    - libavahi-client-dev
    - libssl-dev
    - libsoxr-dev

- name: Shairport-sync - git checkout shairport-sync
  become: true
  git:
    repo:  git://github.com/mikebrady/shairport-sync.git
    dest: /home/pi/shairport-sync

- name: Shairport-sync - autoreconf - configure - make - make install
  become: true
  shell: "{{ item }}"
  args:
    chdir: /home/pi/shairport-sync
    creates: /usr/local/bin/shairport-sync
  with_items:
    - autoreconf -i -f
    - ./configure --with-alsa --with-avahi --with-ssl=openssl --with-soxr --with-metadata --with-stdout --with-systemd
    - make
    - make install

- name: Shairport-sync - systemd
  become: true
  systemd:
    name: shairport-sync
    state: stopped
    enabled: no

- name: Shairport-sync - copy config file
  become: true
  copy: 
    src: /home/pi/rel-stretch/usr/local/etc/shairport-sync.conf
    dest: /usr/local/etc/shairport-sync.conf
    remote_src: yes

#Squeezelite
- name: Squeezelite - copy precompiled binarys armv6l
  become: true
  copy: 
    src: /home/pi/rel-stretch/other/squeezelite/squeezelite-1.8.7-999-armv6l
    dest: /usr/local/bin/squeezelite-armv6l
    remote_src: yes
  when: "ansible_architecture == 'armv6l'"

- name: Squeezelite - copy precompiled binarys armv7l
  become: true
  copy: 
    src: /home/pi/rel-stretch/other/squeezelite/squeezelite-1.8.7-999-armv7l
    dest: /usr/local/bin/squeezelite-armv7l
    remote_src: yes
  when: "ansible_architecture == 'armv7l'"

#Upmpdcli
- name: Upmpdcli - install packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - libmicrohttpd-dev
    - libexpat1-dev
    - libxml2-dev
    - libxslt1-dev
    - libjsoncpp-dev
    - python-requests
    - python-pip

- name: Upmpdcli - install gmusicapi with pip
  become: true
  pip:
    name: gmusicapi

- name: Upmpdcli - copy libupnp-jfd5 archive
  become: true
  copy: 
    src: /home/pi/rel-stretch/other/upmpdcli/libupnp-1.6.20.jfd5.tar.gz
    dest: /home/pi
    remote_src: yes

- name: Upmpdcli - untar libupnp-jfd5 archive
  become: true
  unarchive:
    src: /home/pi/libupnp-1.6.20.jfd5.tar.gz
    dest: /home/pi
    remote_src: yes

- name: Upmpdcli - libupnp-jfd5 autoreconf - configure - make - make install
  become: true
  shell: "{{ item }}"
  args:
    chdir: /home/pi/libupnp-1.6.20.jfd5
    creates: /usr/lib/libupnp.so.6.3.4
  with_items:
    - ./configure --prefix=/usr --sysconfdir=/etc
    - make
    - make install

- name: Upmpdcli - copy libupnp archive
  become: true
  copy: 
    src: /home/pi/rel-stretch/other/upmpdcli/libupnpp-0.16.0.tar.gz
    dest: /home/pi
    remote_src: yes

- name: Upmpdcli - untar libupnp archive
  become: true
  unarchive:
    src: /home/pi/libupnpp-0.16.0.tar.gz
    dest: /home/pi
    remote_src: yes

- name: Upmpdcli - libupnp - configure - make - make install
  become: true
  shell: "{{ item }}"
  args:
    chdir: /home/pi/libupnpp-0.16.0
    creates: /usr/lib/libupnpp.so.7.0.0
  with_items:
    - ./configure --prefix=/usr --sysconfdir=/etc
    - make
    - make install


- name: Upmpdcli - copy upmpdcli archive
  become: true
  copy: 
    src: /home/pi/rel-stretch/other/upmpdcli/upmpdcli-1.2.15.tar.gz
    dest: /home/pi
    remote_src: yes

- name: Upmpdcli - untar upmpdcli archive
  become: true
  unarchive:
    src: /home/pi/upmpdcli-1.2.15.tar.gz
    dest: /home/pi
    remote_src: yes

- name: Upmpdcli - upmpdcli - configure - make - make install
  become: true
  shell: "{{ item }}"
  args:
    chdir: /home/pi/upmpdcli-1.2.15
    creates: /usr/bin/upmpdcli
  with_items:
    - ./configure --prefix=/usr --sysconfdir=/etc
    - make
    - make install

- name: Upmpdcli - upmpdcli create user
  become: true
  user:
    name: upmpdcli

- name: Upmpdcli- upmpdcli copy contents
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
    - { src: '/home/pi/rel-stretch/lib/systemd/system/upmpdcli.service', dest: '/lib/systemd/system/upmpdcli.service' }
    - { src: '/home/pi/rel-stretch/etc/upmpdcli.conf', dest: '/etc/upmpdcli.conf' }

- name: Upmpdcli - disable service
  become: true
  systemd:
    name: upmpdcli
    state: stopped
    enabled: no
    daemon_reload: yes

#upexplorer
- name: upexplorer - git checkout upexplorer
  become: true
  git:
    repo:  https://@opensourceprojects.eu/git/p/libupnppsamples/code
    dest: /home/pi/libupnppsamples-code

- name: upexplorer - autogen.sh - configure - make - make install
  become: true
  shell: "{{ item }}"
  args:
    chdir: /home/pi/libupnppsamples-code
    creates: /usr/local/bin/upexplorer
  with_items:
    - ./autogen.sh
    - ./configure
    - make
    - make install

#Final clean up
- name: delete build dirs and files
  become: true
  file: 
    state: absent
    path: "{{ item }}"
  with_items:
    - /home/pi/ashuffle
    - /home/pi/mpdas/mpdas
    - /home/pi/shairport-sync
    - /home/pi/libupnp-1.6.20.jfd5
    - /home/pi/libupnpp-0.16.0
    - /home/pi/upmpdcli-1.2.15
    - /home/pi/libupnppsamples-code

- name: apt clean
  become: true
  apt:
    autoclean: yes

- name: clear syslogs
  become: true
  shell: /var/www/command/util.sh clear-syslogs

- name: reboot
  become: true
  shell: shutdown -r +1
  async: 0
  poll: 0

- name: wait for pi to return after reboot
  local_action: wait_for_connection host={{ ansible_hostname }} state=started port=22 delay=30 timeout=120
