- name: Step 3 - swapfile off
  become: true
  shell: dphys-swapfile swapoff && update-rc.d dphys-swapfile remove && rm -rf /var/swap

- name: Step 3 - disable cron.service
  become: true
  systemd:
    name: cron.service
    state: stopped
    enabled: no

- name: Step 3 - enable rpcbind
  become: true
  systemd:
    name: rpcbind
    state: started
    enabled: yes

- name: Step 3 - purge triggerhappy
  become: true
  apt: name=triggerhappy state=absent

- name: Step 3 - update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day. Update the apt cache if its older than the cache_valid_time. 

- name: Step 3 - install core packages
  become: true
  apt: name={{item}} state=present
  with_items:
    - rpi-update
    - php-fpm
    - nginx
    - sqlite3
    - php-sqlite3
    - memcached
    - php-memcache
    - mpc
    - bs2b-ladspa
    - libbs2b0
    - libasound2-plugin-equal
    - telnet
    - automake
    - sysstat
    - squashfs-tools
    - tcpdump
    - shellinabox
    - samba
    - smbclient
    - udisks-glue
    - ntfs-3g
    - exfat-fuse
    - git
    - inotify-tools
    - libav-tools
    - avahi-utils

- name: Step 3 - disable shellinabox
  become: true
  systemd:
    name: shellinabox
    state: stopped
    enabled: no