- name: Step 2 - download moode sources
  get_url:
    url: http://moodeaudio.org/downloads/beta/rel-stretch-r40b9.zip
    dest: /home/pi
    checksum: md5:4dd1ace90cf34f146615a0e292d597ba

- name: Step 2 - extract moode sources
  unarchive:
    src: /home/pi/rel-stretch-r40b9.zip
    dest: /home/pi
    remote_src: yes