- name: Step 2 - download moode sources
  get_url:
    url: http://moodeaudio.org/downloads/beta/rel-stretch-r40b11.zip
    dest: /home/pi
    checksum: md5:7ba33c12bf05b3c381dbc92b0516e381

- name: Step 2 - extract moode sources
  unarchive:
    src: /home/pi/rel-stretch-r40b11.zip
    dest: /home/pi
    remote_src: yes